services:
  app:
    build: .
    ports:
      - "8081:8080" # container 8080 mapped to host 8081
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mymemory
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mymemory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5435:5432" # container 5432 mapped to host 5435
